runtime: python37

instance_class: F2

handlers:

- url: /css
  static_dir: vue/dist/css
  secure: always
  redirect_http_response_code: 301

- url: /img
  static_dir: vue/dist/img
  secure: always
  redirect_http_response_code: 301

- url: /js
  static_dir: vue/dist/js
  secure: always
  redirect_http_response_code: 301

- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
