name: Build and Deploy to Google App Engine

on:
  push:
    branches:
    - master

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Set up Python 3.7
      uses: actions/setup-python@master
      with:
        python-version: 3.7

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Install Yarn Dependencies
      uses: borales/actions-yarn@v2.0.0
      with:
        entrypoint: /bin/sh
        args: -c cd vue; yarn install

    - name: Lint Vue
      uses: borales/actions-yarn@v2.0.0
      with:
        entrypoint: /bin/sh
        args: -c cd vue; yarn lint --no-fix

    - name: Build Static HTML
      uses: borales/actions-yarn@v2.0.0
      with:
        entrypoint: /bin/sh
        args: -c cd vue; yarn build

    - name: Setup gcloud CLI
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
         version: '270.0.0'
         service_account_email: ${{ secrets.GAE_SERVICE_ACCOUNT_EMAIL }}
         service_account_key: ${{ secrets.GAE_SERVICE_ACCOUNT_KEY }}

    - name: Deploy
      run: gcloud --quiet --project dedbeetz app deploy
